language: python
python:
  - 2.7

services:
  - docker

install: skip

jobs:
  include:
  - stage: Build
    script: docker build -t lazytechw/postgres-barman:v12.2 ./postgres
  - script: docker build -t lazytechw/barman-docker:v12.2 ./barman
  - stage: Test
    script:
    - cd examples
    - docker-compose up -d
    - bash execDockerInit.sh
    - bash test.sh

